version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: deans_office_java
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=electronicDeansOffice_db
      - POSTGRES_HOST_AUTH_METHOD=trust
