server:
  port: 5999
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
    include-stacktrace: on_param

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Deanery
    username: postgres
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
        jdbc:
          batch_size: 30
          batch_versioned_data: true
        order_updates: true
        order_inserts: true
        default_batch_fetch_size: 30
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  main:
    allow-circular-references: true

  sql:
    init:
      mode: always
      platform: all
